version: 0.2

artifacts:
   files:
      - '**/*'

phases:
   install:
      runtime-versions:
         php: latest
      commands:
         - echo "installing something"
   pre_build:
      commands:
         - echo "we are in the pre build phase"
   build:
      commands:
         - echo "we are in the build block"
         - echo "we will run some tests"
         - grep -Fq "Developer News" welcome.php
         
   post_build:
      commands:
         - echo "we are in the post build phase"
